[versions]
agp = "9.1.1"
kotlin = "2.3.20"
android-minSdk = "23"
android-compileSdk = "36"
vanniktechMavenPublish = "0.36.0"
kotlinStdlib = "2.3.20"
runner = "1.5.2"
core = "1.5.0"
junit = "1.1.5"
dokka = "2.2.0"
compose-multiplatform = "1.11.1"
compose-material3 = "1.11.0-alpha07"
compose-ui = "1.11.1"
compose-foundation = "1.11.1"
compose-runtime = "1.11.1"
kotlinx-collections-immutable = "0.5.0"
compose-material = "1.7.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
core = { group = "androidx.test", name = "core", version.ref = "core" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
compose-material-icons = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
androidx-activity-compose = "androidx.activity:activity-compose:1.9.3"
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable"}

[plugins]
androidApp = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
